-- Adminer 4.8.1 MySQL 8.0.31 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `eventos`;
CREATE TABLE `eventos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tipo` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
  `valor` date DEFAULT NULL,
  `inicio` date DEFAULT NULL,
  `fin` date DEFAULT NULL,
  `valores` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `actividad` text COLLATE utf8mb4_general_ci NOT NULL,
  `porcentaje` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
  `evidencia` text COLLATE utf8mb4_general_ci NOT NULL,
  `responsable` text COLLATE utf8mb4_general_ci NOT NULL,
  `estado` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
  `id_usuario` int NOT NULL,
  `fecha_registro` datetime NOT NULL,
  `fecha_actualizacion` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_usuario` (`id_usuario`),
  CONSTRAINT `eventos_ibfk_1` FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

<<<<<<< HEAD
INSERT INTO `eventos` (`id`, `tipo`, `valor`, `inicio`, `fin`, `valores`, `actividad`, `porcentaje`, `evidencia`, `responsable`, `estado`, `id_usuario`, `fecha_registro`, `fecha_actualizacion`) VALUES
(1,	'unico',	'2023-10-02',	NULL,	NULL,	NULL,	'Verificación de apertura de aplicativos institucionales.',	'1.66',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EmfgxZ1my2hJhYMe8a5riEoB2DU23BkyUOlwmgmouaTcig?e=PpeeYL',	'Dirección de Sistemas y Tecnología, Oficina Desarrollo Académico',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(2,	'rango',	NULL,	'2023-10-03',	'2023-10-04',	NULL,	'Revisión en el aplicativo de los grupos del 2024-1 para el registro de grupos, cupos y horarios para núcleos temáticos y campos de aprendizaje disciplinares.',	'3.32',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ejoit4P7hi1Po0PCuRc3TFcBW-ySucvbYw5Pzt9Geuqw7w?e=ua7b8V',	'Dirección de Sistemas y Tecnología',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(3,	'unico',	'2023-10-05',	NULL,	NULL,	NULL,	'Socialización Ruta Inicio Actividades Académicas 2024-1',	'4.98',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Em0Y81Q79TpInbzGwjHUI6oBXxoeBYLuNcTdbn4F3G2cvA?e=q8EDm2',	'Oficina Desarrollo Académico',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(4,	'unico',	'2023-10-06',	NULL,	NULL,	NULL,	'Inducción - Reinducción, Planeación de la Actividad Académica: Lineamientos Institucionales, Socialización RIAA-2024-1. Manejo del software - aplicativos institucionales. Acompañamiento Equipo Institucional.',	'6.64',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EpTY5dBrWKVFmW3aYPzfTyQB_w1i9GXiKmz0a2C55DqOoA?e=hBLeKh',	'Dirección de Sistemas y Tecnología, Oficina Desarrollo Académico y Unidad de Apoyo Académico',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(5,	'rango',	NULL,	'2023-10-09',	'2023-10-10',	NULL,	'Entrega de analítica del comportamiento de la Zona CAI y TR definida para las sedes de la UCundinamarca (Número de grupos, capacidades y franjas horarias).',	'8.3',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eias31IDs9ZNsD9d0nN96wUBUqgh81elqR-eLZ_0Z-jIJg?e=WbbebO',	'Oficina Desarrollo Académico, Coordinadores áreas transversales, Líderes CAI',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(6,	'rango',	NULL,	'2023-10-11',	'2023-10-13',	NULL,	'Verificación y creación de requerimientos de los núcleos temáticos transversales y campos de aprendizaje institucionales.',	'9.96',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EvCG8556XCdBigLQx3M2RkcBp7jiYtxNE2UnIuq-DfzD3A?e=WoF5C9',	'Oficina Desarrollo Académico',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(7,	'unico',	'2023-10-17',	NULL,	NULL,	NULL,	'Reporte mediante correo electrónico a las Direcciones y Coordinaciones de los Programas Académicos de los grupos, cupos y horarios establecidos para los núcleos temáticos transversales y campos de aprendizaje institucionales.',	'11.62',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EvZNUS52kAdNtltvfA8Zt_gB69QPZJd0kXfZxchyO47YIQ?e=ZBQAyO',	'Oficina Desarrollo Académico',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(8,	'rango',	NULL,	'2023-10-18',	'2023-10-20',	NULL,	'Registro de grupos, cupos y horarios para el 2024-1 en el aplicativo institucional por parte de los Coordinadores de Programas Académicos Disciplinares',	'13.28',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EgcKBGLaI6ZBrNUGaexialIBxnxk4h2qbA2A5zPkFqlFpg?e=QZt6rA',	'Directores y Coordinadores programas académicos pregrado y posgrado',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(9,	'rango',	NULL,	'2023-10-23',	'2023-10-25',	NULL,	'Revisión de: Grupos, Cupos, horarios por parte de la Oficina Desarrollo Académico',	'14.94',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ege3qV6ZHshLm6cG7e24LEUBFBP7-OQSQch3pGlGwH1KOA?e=JXHauy',	'Dirección de Sistemas y Tecnología, Oficina Desarrollo Académico',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(10,	'unico',	'2023-10-27',	NULL,	NULL,	NULL,	'Envío de resultados correspondientes a convocatorias institucionales CTI e ISU.',	'16.6',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Er5pCq_TwBJLjm4xRK01QRQB_Rn2zjSrAYq-oG9sDOwsdg?e=1XjpYR',	'Dirección de Investigación, Interacción Social Universitaria',	'completo',	1,	'2023-10-02 00:00:00',	NULL),
(11,	'rango',	NULL,	'2023-10-30',	'2023-11-01',	NULL,	'Proyección en la herramienta digital de la asignación docente (previo registro en el aplicativo institucional).',	'18,26',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EuVa_DJTXRVOowBRC495FSQB__L-kkD3R7pQmMG1rq2Dog?e=KyYgac',	'Direcciones y Coordinaciones de programas académicos, Instituto de Posgrados, Oficina Desarrollo Académico.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(12,	'rango',	NULL,	'2023-11-01',	'2023-11-03',	NULL,	'Verificación de la proyección de la asignación docente (previo registro en el aplicativo institucional).',	'19,92',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ekntqsv9LDRLjO_EJfXfruABIo-CsUottbfFKGTTrhrICQ?e=xexTE7',	'Oficina Desarrollo Académico, Direcciones y Coordinaciones de programas académicos, Instituto de Posgrados.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(13,	'rango',	NULL,	'2023-11-07',	'2023-11-08',	NULL,	'Proyección y Asignación Docente (Programas de pregrado y posgrado). Acuerdo del Consejo Académico No. 006 de 2016.',	'21,58',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ei2plz9WhBxFkawv_kS7534BrRwaAu9FeMyRgcxWFqcmcw?e=1DeR0j',	'Oficina Desarrollo Académico, Direcciones y Coordinaciones de programas académicos, Instituto de Posgrados.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(14,	'rango',	NULL,	'2023-11-09',	'2023-11-10',	NULL,	'Analítica requerimientos registrados en el aplicativo y en la plataforma académica: -Proyección de grupos, cupos y horarios. -Proyección de la asignación docente (Programas académicos de pregrado y posgrado).',	'23,24',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ep9dAN-P1OBPo5STwd_AElsBYZZKBXNtrzzeQSHDPQur7w?e=9DVibo',	'Oficina Desarrollo Académico',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(15,	'unico',	'2023-11-10',	NULL,	NULL,	NULL,	'Cierre del aplicativo institucional para la asignación docente.',	'24,9',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eqk3g3hfIYJEoyAMKPldmM0BO48FeelKwt40sydrCf86tg?e=r4PdAu',	'Oficina Desarrollo Académico, Dirección de Sistemas y Tecnología',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(16,	'rango',	NULL,	'2023-11-13',	'2023-11-20',	NULL,	'Preasignación de Espacios Académicos',	'26,56',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eqo3k4lM2ElMojhllkYiiYABPEVGgZwGKszxHD30bV3loQ?e=1iamvd',	'Unidad de Apoyo Académico',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(17,	'rango',	NULL,	'2023-11-14',	'2023-11-16',	NULL,	'Mesas de Trabajo por Facultad y Dirección del Instituto de Posgrados',	'28,22',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ev4BvSF3B25Diqn3tJsprX4BFFPfqVem3Xt8yzBjLAwt7Q?e=eBPe4l',	'Oficina de Desarrollo Académico, Decanaturas de Facultad, Dirección Instituto de Posgrados, Coordinaciones y Direcciones de programas académicos pregrado y posgrado',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(18,	'varios',	NULL,	NULL,	NULL,	'2023-11-14, 2023-11-17, 2023-11-20',	'Registro del resultado final de la evaluación de aprendizajes en la plataforma institucional período 2023-2. Cierre plataforma institucional',	'29,88',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EuUBB0fWXOtJnFtvZu7XtXEB79JFJZNgwOZR0nLVq8Iq6Q?e=ta12cQ',	'Decanaturas de Facultad, Dirección Instituto de Posgrados, Coordinaciones y Direcciones Programas Académicos, Oficina de Admisiones y Registro',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(19,	'unico',	'2023-11-17',	NULL,	NULL,	NULL,	'Extracción del resultado final de la evaluación del aprendizaje (Plataforma Moodle a Plataforma Académica). Cierre período académico 2023-1 Pregrado y Posgrado.',	'31,54',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/En19LBhtGLtJkskjtgNMaQABFbJQiISuA3Vq4W7NHdq67A?e=yG7ZS9',	'Oficina de Admisiones y Registro, Oficina de Educación Virtual y a Distancia, Decanaturas de Facultad, Dirección Instituto de Posgrados, Dirección Sistemas y Tecnología',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(20,	'varios',	NULL,	'2023-11-17',	'2023-11-21',	NULL,	'Ruta de verificación de los Campos de aprendizaje digitales (CAI y CADI).',	'33,2',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Emk-E_xhJDlHjWYAQegsWVIBDSLACnseWGS3arAO_HTkAg?e=wJZXAX',	'Oficina de Educación Virtual y a Distancia, Coordinaciones y Direcciones programas académicos pregrado y posgrado. (Rutas de aprendizaje en despliegue y proyectadas 2023-2).',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(21,	'unico',	'2023-11-24',	NULL,	NULL,	NULL,	'Información de la aprobación de la opción de grado (Semestre avanzado por programa académico). Aplica en planes de estudio - Reglamento Estudiantil - Acuerdo C.S. No. 010 de 2006.',	'34,86',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EkvhZb6_xaBMrtw9ABbXCSwBaIGfMLpnHHiptKkWVPqJOg?e=gS3IpA',	'Decanaturas de Facultad, Coordinaciones Y Direcciones Programas académicos, Oficina de Admisiones y Registro',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(22,	'unico',	'2023-11-24',	NULL,	NULL,	NULL,	'Entrega de la información de los estudiantes que cumplen con el requisito de sustentación y aprobación de la opción de grado. Implementación del Aplicativo Opción de Grado (Actas Sustentación)',	'36,52',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EkkvEyoA-t1OtZXmVhA_tgcBsF28C0HYCxWzcy1KIpCSnQ?e=wwJPJW',	'Decanaturas de Facultad Dirección Instituto de Posgrados Coordinaciones y Direcciones Programas Académicos',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(23,	'unico',	'2023-11-24',	NULL,	NULL,	NULL,	'Cierre Plataforma módulo asignación docente',	'38,18',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EgMbUxmsz1FGkzvXtHL54acBeDOVLeudD-g0UFCAVvEGwQ?e=iQIDnn',	'Oficina Desarrollo Académico, Dirección Sistemas y Tecnología',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(24,	'varios',	NULL,	NULL,	NULL,	'2023-11-27, 2023-11-30',	'Revisión ajustes a la asignación Académica y Espacios Académicos',	'39,84',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eiwu-ZeqQ0BOljfS-2vh7isBDqF3Vx5g4COet_BT2URyQw?e=KUIVwc',	'Oficina de Desarrollo Académico, Unidad de Apoyo Académico, Dirección de Sistemas y Tecnología.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(25,	'rango',	NULL,	'2023-11-01',	'2023-12-01',	NULL,	'Convocatoria (Banco de Talento Académico pregrado y posgrado).',	'41,5',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EmE77ZSrm7BHo2_AMILp5j0B1hsrP6GW15V9vGkXI06Bnw?e=HnzjWk',	'Vicerrectoría Académica, Decanaturas de Facultad, Vicerrectoría Académica, Dirección de Talento Humano',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(26,	'rango',	NULL,	'2023-12-01',	'2024-01-02',	NULL,	'Asignación de puntaje y categorización docente',	'43,16',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EsQJxg21hQxJl49LkZ6urWcB4ayD9InsXSD6uP3E4yZgMQ?e=RKsGW4',	'Comité del Profesor, Comité Interno de Asignación de Puntaje',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(27,	'varios',	NULL,	NULL,	NULL,	'2024-01-09, 2024-01-11',	'Verificación requisitos de contratación docente',	'44,82',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EsNmZIuPSUBEoOf99nrAysABakD0sXHPo0m3193RIYhdBg?e=i6HD37',	'Dirección de Talento Humano, Coordinaciones y Direcciones, Programas Académicos pregrado y posgrado',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(28,	'unico',	'2024-01-09',	NULL,	NULL,	NULL,	'Entrega de la Asignación de la dedicación docente en medio digital y debidamente firmado por el decano en original a la Oficina de Desarrollo Académico.',	'46,48',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/ElAlpOVs5dBCsjVUsCV9mlYBjlqcL8CP6Lr98bx4eY_1Yw?e=td7drI',	'Decanos de Facultad, Dirección Instituto de Posgrados, Oficina Desarrollo Académico.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(29,	'unico',	'2024-01-10',	NULL,	NULL,	NULL,	'Solicitud de CDP por programa académico',	'48,14',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EiqYu9ht2EdPh_i1uy4zIkUBZmvghi666V58gD0UL9ex-A?e=LqjkWQ',	'Vicerrectoría Académica, Oficina Desarrollo Académico',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(30,	'unico',	'2024-01-12',	NULL,	NULL,	NULL,	'Legalización solicitud CDP por programa académico',	'49,8',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ehj58ySHBtRFgy76eDUoAcUBoRZLVstd56nmMZE2OGmnfA?e=pu4uYJ',	'Vicerrectoría Administrativa y Financiera, Dirección Financiera Presupuesto Rectoría',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(31,	'unico',	'2024-01-15',	NULL,	NULL,	NULL,	'Entrega CDP a los programas académicos (Contratación Docente).',	'51,46',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ep4Zx_qGaidFsFEmhKBv9tMBj7q7hVB1WctGCMSPbBd1Lw?e=FshIcJ',	'Vicerrectoría Académica, Vicerrectoría Administrativa y Financiera, Oficina Desarrollo Académico',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(32,	'rango',	NULL,	'2024-01-15',	'2024-01-19',	NULL,	'Exámenes médicos de Ingreso Contratación Docentes.',	'53,12',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EgNScrxWK-lCkbN9rrQYlVMBCB4jxA1VbVLiC6l2jz7a6g?e=Eti1L2',	'Dirección de Talento Humano-SST',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(33,	'rango',	NULL,	'2024-01-16',	'2024-01-22',	NULL,	'Contratación Docente',	'54,78',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Et-UHpW-4NRPvfA6rKV7NkQB50BQveRE8112ad2Rky9lRg?e=uNj3Hs',	'Dirección Talento Humano, Gestores Talento Humano de las sedes, Directores Administrativos sedes, Decanos de Facultad y Dirección del Instituto de Posgrados.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(34,	'rango',	NULL,	'2024-01-18',	'2024-01-31',	NULL,	'Solicitud y Expedición de RP por contrato',	'56,44',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EuhEZ9y93x1Am9kbzb4KwLwBIum4r5ti14EVZ0AjAwoDOw?e=wgR69f',	'Oficina Desarrollo Académico, Dirección de Talento Humano, Presupuesto',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(35,	'unico',	'2023-11-24',	NULL,	NULL,	NULL,	'Información estudiantes en movilidad saliente 2024-1',	'58,1',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ejmxz5NWSvtBvHFKzFG6L0IBdKRJF8XG48YbGZgvttkH6g?e=05Hb3K',	'Líder Dialogando con el Mundo, Coordinaciones/Direcciones programas académicos',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(36,	'unico',	'2023-12-07',	NULL,	NULL,	NULL,	'Publicación Listados de Estudiantes Admitidos 2024-1',	'59,76',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ei7ikd-dPTFDg9CXDpNNUPEBCtZO7q8R0hav_dClWDEeqQ?e=SbO14V',	'Oficina de Admisiones y Registro, Coordinaciones/Direcciones programas académicos',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(37,	'rango',	NULL,	'2024-01-08',	'2024-01-15',	NULL,	'Caracterización de estudiantes nuevos, antiguos y transferencias externas y reingresos.',	'61,42',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EoYMfipTBW1PpL1quyKfZUgBo1AyKy8zozGT5_fwyNRVkQ?e=nXTMXh',	'Oficina de Admisiones y Registro, Dirección Sistemas y Tecnología.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(38,	'rango',	NULL,	'2024-01-02',	'2024-01-12',	NULL,	'Generación de Recibos de Pago Estudiantes Nuevos',	'63,08',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EthH264bd9ZEpyvQDr49UEgBTTzIyG7TdQNdxz_2wgVG4w?e=JrgJMe',	'Vicerrectoría Administrativa y Financiera, Tesorería, Dirección de Sistemas y Tecnología.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(39,	'rango',	NULL,	'2024-01-02',	'2024-01-12',	NULL,	'Pago de matrícula estudiantes nuevos (2024-1)',	'64,74',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EkBq6jGIg3tNsdYEkwDaq7gBmnMWi2rZk5rq_GRiDQRPeA?e=czt9Ed',	'Vicerrectoría Administrativa y Financiera, Dirección Financiera, Tesorería.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(40,	'rango',	NULL,	'2024-01-02',	'2024-01-12',	NULL,	'Pago de matrícula estudiantes nuevos (2024-1).',	'66,4',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eu6KkH0cSstBmhAErrGXNYMBHKawYkLt4hHyS8ujfyfdAg?e=cgUq2b',	'Vicerrectoría Administrativa y Financiera, Dirección Financiera, Tesorería.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(41,	'unico',	'2023-11-18',	NULL,	NULL,	NULL,	'Apertura convocatoria fraccionamiento de matrícula.',	'68.06',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Erh_c16lXPtBmCQ0QVbBtc4BUpPiPp6leBu4zDG3-HpTDA?e=2Zi2jn',	'Oficina Apoyo Financiero',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(42,	'unico',	'2023-10-30',	NULL,	NULL,	NULL,	'Publicación aprobación de fraccionamiento de matrícula',	'69.72',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EoF4H3jKfLRAhOWRIxylpN0BZaMylb-gtwJzxjypvJ37hw?e=K0hnIw',	'Vicerrectoría Administrativa y Financiera, Oficina Apoyo Financiero',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(43,	'unico',	'2023-10-30',	NULL,	NULL,	NULL,	'Expedición Resolución de exoneraciones',	'71.38',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EsqItRHvmIdBlmtSKI83uxwBoonJScgSJub1JtN8M44oeA?e=HmaGZv',	'Vicerrectoría Administrativa y Financiera, Oficina Apoyo Financiero.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(44,	'unico',	'2023-10-24',	NULL,	NULL,	NULL,	'Solicitud de CDP de Exoneraciones de Matrícula',	'73.04',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ev4mWne9QB5MpqBMg6zqKH8BMKh3ffL4MgGcFXS5y9e1fA?e=hd9bGg',	'Vicerrectoría Académica, Dirección de Bienestar Universitario',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(45,	'rango',	NULL,	'2023-10-25',	'2023-10-30',	NULL,	'Legalización de CDP de Exoneraciones de Matrícula',	'74.7',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EqQgWgpwxqBHoYgvjLPKGRMBWplX_c182f-NP3_W18RYEQ?e=H0xD04',	'Vicerrectoría Académica, Dirección de Bienestar Universitario',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(46,	'rango',	NULL,	'2023-12-01',	'2023-12-05',	NULL,	'Expedición de CDP de Exoneraciones de Matrícula',	'76.36',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eu9f7dA_E8xFpF08yd6wn1oBmQ6-SRNYHmmsyJW5A6RegQ?e=3DHBf1',	'Vicerrectoría Académica, Dirección de Bienestar Universitario',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(47,	'rango',	NULL,	'2023-12-06',	'2023-12-08',	NULL,	'Solicitud RP de Exoneraciones de Matrícula',	'78.02',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/ElKE3eXrOQdArBHmk9lRai0BlTyJoOxTKjm0AbsoL0bICQ?e=X0JgcN',	'Vicerrectoría Académica, Dirección de Bienestar Universitario',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(48,	'rango',	NULL,	'2023-12-11',	'2023-12-14',	NULL,	'Solicitud RP de Exoneraciones de Matrícula',	'79.68',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EpPMY5wZW9BBjJTVPRk7fcoBES3wgNPgg0eEeKz0q0Zq8g?e=nPVO9d',	'Vicerrectoría Académica, Dirección de Bienestar Universitario',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(49,	'rango',	NULL,	'2024-01-02',	'2024-01-19',	NULL,	'Pago de matrícula estudiantes antiguos',	'81.34',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ekg6Ci6kH65HsBTkQKYGmBEBAPFXqwxPiZ4LWMKQ9Igh2Q?e=xnoqgz',	'Oficina de Admisiones y Registro, Dirección de Sistemas y Tecnología, Tesorería, Dirección Financiera',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(50,	'unico',	'2024-01-22',	NULL,	NULL,	NULL,	'Actualización estado de pagos periodo 2023-2',	'83',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EvBHjp1mmtxMnxP33qhDVX8BJDxs9iCiuvtcuJT1FE_--A?e=Ge6Uid',	'Dirección Financiera, Tesorería, Dirección de Sistemas y Tecnología',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(51,	'Rango',	NULL,	'2024-01-23',	'2024-01-26',	NULL,	'Registro académico estudiantes nuevos',	'84,66',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EtBI7IxT64dMh_KiNGiAnbsBMngoXK2QUjFfrnBzXKOQqQ?e=4yT1p8',	'Oficina de Admisiones y Registro',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(52,	'Rango',	NULL,	'2024-01-23',	'2024-01-29',	NULL,	'Registro académico de diagnósticos y nivelatorios a los estudiantes nuevos y antiguos.',	'86,32',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EivCuutNAalIsBf4pjcDzokBO0kXz7hi1tvScbt2lPgwFw?e=t221W6',	'Secretaria general, Dirección de Sistemas y Tecnología, Oficina Admisiones y Registro',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(53,	'Unico',	'2024-01-15',	NULL,	NULL,	NULL,	'Solicitud y publicación de horarios, espacios académicos, docente asignado.',	'87,98',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/ErwrbcZEhipHvieqM3h9z_ABogvREfm3Fmk-R1Xrdn-0HQ?e=nmC2xF',	': Oficina Desarrollo Académico. Unidad Apoyo Académico, Dirección de Sistemas y Tecnología.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(54,	'Rango',	NULL,	'2024-01-29',	'2024-02-01',	NULL,	'Registro Académico 2024-1 estudiantes antiguos.',	'89,64',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Ev4wTscvn9NIr0wXvl9Tal8BRTYe6Qj90HVQECVMXM0KaQ?e=EoKWdU',	'Dirección de Sistemas y Tecnología, Oficina de Admisiones y Registro, Coordinaciones / Direcciones, programas académicos.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(55,	'Unico',	'2024-02-02',	NULL,	NULL,	NULL,	'Registro académico 2024-1 (Casos especiales-novedades)',	'91,3',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EvTadGhsZf1Mq7zjU2r-xBIB5fKm299AZY9qRj6LWMNExw?e=jI6yCZ',	'Coordinadores y directores de Programa Académico.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(56,	'Rango',	NULL,	'2024-01-24',	'2024-02-02',	NULL,	'Verificación de la vinculación masiva de docentes a los grupos creados',	'92,96',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EvMY4sTy4dxGk89Sl_7eljsB9kRAsfdtXJAPnxJ739w0CA?e=UEhLXS',	'Dirección de Sistemas y Tecnología, Oficina Desarrollo Académico',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(57,	'Rango',	NULL,	'2024-01-29',	'2024-02-02',	NULL,	'Creación Equipos Teams',	'94,62',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EmDnfXzOjxVDk6LPcwSJydYBnJGuGZr06OQiOSCkWuyenQ?e=q6EfGm',	'Dirección de Sistemas y Tecnología, Oficina Desarrollo Académico',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(58,	'Rango',	NULL,	'2024-02-01',	'2024-02-02',	NULL,	'Verificación asignación Espacios Académicos.',	'96,28',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Eu5DMjGYRaBBgr4p76sHShUBqTDn6x9DeA_vZPR7UNftGg?e=7FsUFb',	'Unidad de Apoyo Académico.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(59,	'Rango',	NULL,	'2024-02-01',	'2024-02-02',	NULL,	'Mesa de trabajo permanente.',	'98,14',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/EsKt2kpsMAlBqygoVKjIujkBRLSrQfz2J8NFJEObgzganw?e=TgUtF3',	'Dirección de Sistemas y Tecnología, Oficina de Educación Virtual y a Distancia, Oficina Desarrollo Académico.',	'completo',	1,	'2023-10-17 00:00:00',	NULL),
(60,	'Unico',	'2024-02-05',	NULL,	NULL,	NULL,	'Inicio de clases.',	'100',	'https://mailunicundiedu-my.sharepoint.com/:f:/g/personal/desarrolloacademicoaunclic_ucundinamarca_edu_co/Em19bOORfN1DhFqwJ5ipVU4B6U2wYI8ITB1haOrC1lwckw?e=la49F2',	'Vicerrectoría Académica,Vicerrectoría Administrativa y Financiera, Decanaturas de Facultad, Coordinaciones y Direcciones programas y Dirección de Bienestar Universitario.',	'completo',	1,	'2023-10-17 00:00:00',	NULL);
=======
>>>>>>> 072d211e1659f0b3923a7f8057525e25db094ac0

DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE `usuarios` (
  `id_usuario` int NOT NULL AUTO_INCREMENT,
  `nombre_usuario` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `apellidos_usuario` varchar(45) COLLATE utf8mb4_general_ci NOT NULL,
  `email_usuario` varchar(125) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password_usuario` text COLLATE utf8mb4_general_ci NOT NULL,
  `fecha_creado` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

<<<<<<< HEAD
INSERT INTO `usuarios` (`id_usuario`, `nombre_usuario`, `apellidos_usuario`, `email_usuario`, `password_usuario`, `fecha_creado`) VALUES
(1,	'Super',	'Admin',	'admin@ucundinamarca.edu.co',	'$2y$10$FHJ3d6PbMfvWbdrUWfiel.3Lyo/1u8bYLDYSXMHu3RQuLHRaV91tG',	'2023-10-17 20:50:52');

-- 2023-10-17 21:33:16
=======

-- 2023-10-17 20:06:30
>>>>>>> 072d211e1659f0b3923a7f8057525e25db094ac0
